import type { TipsResponse } from "./types"

// DANE TESTOWE (mock) — zgodne z kontraktem `GET /public-api/tips/today`.
// Zostaną zastąpione realnym fetchem do Oracle w lib/tips.ts.
// Thriller celowo obecny w danych — UI ukrywa go w MVP.
export const mockTips: TipsResponse = {
  date: "2026-06-03",
  tips: [
    {
      event_id: 1001,
      league: "Premier League",
      home: "Arsenal",
      away: "Chelsea",
      kickoff_utc: "2026-06-03T19:00:00Z",
      bet_type: "BTTS",
      bet_side: "YES",
      model_prob: 0.71,
      odds: 1.65,
      edge: 0.08,
      q_score: 82,
      actual_result: null,
    },
    {
      event_id: 1002,
      league: "La Liga",
      home: "Real Betis",
      away: "Villarreal",
      kickoff_utc: "2026-06-03T20:00:00Z",
      bet_type: "OVER_1_5",
      bet_side: "OVER",
      model_prob: 0.84,
      odds: 1.28,
      edge: 0.05,
      q_score: 76,
      actual_result: null,
    },
    {
      event_id: 1003,
      league: "Serie A",
      home: "Atalanta",
      away: "Bologna",
      kickoff_utc: "2026-06-03T18:45:00Z",
      bet_type: "MIX",
      bet_side: "BTTS+OVER",
      model_prob: 0.63,
      odds: 1.9,
      edge: 0.11,
      q_score: 69,
      actual_result: null,
    },
    {
      event_id: 1004,
      league: "Bundesliga",
      home: "Mainz",
      away: "Augsburg",
      kickoff_utc: "2026-06-03T17:30:00Z",
      bet_type: "BTTS",
      bet_side: "YES",
      model_prob: 0.58,
      odds: 1.95,
      edge: 0.03,
      q_score: 54,
      actual_result: null,
    },
    {
      event_id: 1005,
      league: "Ligue 1",
      home: "Lyon",
      away: "Nice",
      kickoff_utc: "2026-06-03T19:15:00Z",
      bet_type: "OVER_1_5",
      bet_side: "OVER",
      model_prob: 0.79,
      odds: 1.34,
      edge: 0.06,
      q_score: 71,
      actual_result: null,
    },
    {
      event_id: 1006,
      league: "Eredivisie",
      home: "AZ Alkmaar",
      away: "Twente",
      kickoff_utc: "2026-06-03T18:00:00Z",
      bet_type: "THRILLER",
      bet_side: "3:2/2:3",
      model_prob: 0.14,
      odds: 8.5,
      edge: 0.19,
      q_score: 61,
      actual_result: null,
    },
  ],
}
